INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(1, 'Diego Alejandro', 'Diaz Paez', 'diego@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(2, 'Laura Vanessa', 'Nieves Castañeda', 'laura@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(3, 'William Leonardo', 'Diaz Gomez', 'william@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(4, 'Daniela Yulieth', 'Diaz Paez', 'daniela@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(5, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(6, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(7, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');

INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(8, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(9, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(10, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(11, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(12, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(13, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(14, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(15, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(16, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(17, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(18, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(19, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(20, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(21, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(22, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(23, 'Nuria Amanda', 'Paez Espejo', 'nuria@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(24, 'Esperanza Moreno', 'Gomez', 'doris@gamil.com', '2020-07-07', '');
INSERT INTO clientes (id, nombre, apellido, email, create_at, foto) VALUES(25, 'Santiago lizarazo', 'Alba Villamizar', 'santiago@gamil.com', '2020-07-07', '');
